### ISSUE TITLE
errors in demo scripts

### ISSUE THREAD

**Issue by dweisz** [bd-j/scombine#4]
Two errors pop up in demo scripts when running in python3.4.4:
1. 

D-10-65-18-150.dhcp4.washington.edu 3:27pm > python example_scombine.py
Traceback (most recent call last):
  File "example_scombine.py", line 11, in <module>
    from sedpy import attenuation, observate
  File "/anaconda/lib/python3.4/site-packages/sedpy-0.1.0-py3.4.egg/sedpy/observate.py", line 12, in <module>
    from yanny import read as yanny_read
ImportError: No module named 'nanny'

but:

from sedpy import yanny 

works just fine.
1. 
## In [4]: %run example_burstysfh.py

ImportError                               Traceback (most recent call last)
/Users/dweisz/Documents/code/scombine/demo/example_burstysfh.py in <module>()
      2 import numpy as np
      3 import fsps
----> 4 import sfhutils as utils
      5 import scombine.bursty_sfh as bsp
      6 from sedpy import attenuation, observate

ImportError: bad magic number in 'sfhutils': b'\x03\xf3\r\n'

**Comment by bd-j** [comment]
just pushed a fix to the demo script.  It works for me on python2.7

you may have to 

```
git pull
python3 setup.py install
```

in both the scombine and sedpy repos to fix the other errors.

**Comment by bd-j** [comment]
example_burstysfh still doesn't work, I heven't updated that demo in awhile.  lemme take a look.

**Comment by bd-j** [comment]
ok, I fixed `example_burstysps` so it runs for me in python2.7.  Try pulling and let me know if you still encounter errors.

**Comment by dweisz** [comment]
One problem solved.  But still not able to find 'yanny' with python3.4.4.  I had to remove python2.7, but can reinstall and try again later to see if that works.

D-10-65-18-150.dhcp4.washington.edu 7:33pm > python example_burstysfh.py
Traceback (most recent call last):
  File "example_burstysfh.py", line 8, in <module>
    from sedpy import attenuation, observate
  File "/anaconda/lib/python3.4/site-packages/sedpy-0.1.0-py3.4.egg/sedpy/observate.py", line 12, in <module>
    from yanny import read as yanny_read
ImportError: No module named 'yanny'
D-10-65-18-150.dhcp4.washington.edu 7:33pm > python example_scombine.py
Traceback (most recent call last):
  File "example_scombine.py", line 13, in <module>
    from sedpy import attenuation, observate
  File "/anaconda/lib/python3.4/site-packages/sedpy-0.1.0-py3.4.egg/sedpy/observate.py", line 12, in <module>
    from yanny import read as yanny_read
ImportError: No module named 'yanny'

and 

## In [3]: from sedpy import observate

ImportError                               Traceback (most recent call last)
<ipython-input-3-cccf758e0243> in <module>()
----> 1 from sedpy import observate

/Users/dweisz/Documents/code/sedpy/sedpy/observate.py in <module>()
     10 except ImportError:
     11     pass
---> 12 from yanny import read as yanny_read
     13 from .reference_spectra import vega, solar, sedpydir
     14

ImportError: No module named 'yanny'

I checked that sedpy is correctly in my path, e.g.,:

In [4]: from sedpy import attenuation

works fine.

**Comment by bd-j** [comment]
the remaining errors were a sedpy problem, should be fixed now.  See bd-j/sedpy#3

pull both scombine and sedpy and reinstall.  The demo scripts run for me in python3.5

**Comment by dweisz** [comment]
ok, looks like the sedpy issues are resolved.  I'll close that issue.  example_scombine.py now works just fine.  example_burstysfh.py yields a small error:

D-10-65-18-150.dhcp4.washington.edu 8:22pm > python example_burstysfh.py
Traceback (most recent call last):
  File "example_burstysfh.py", line 48, in <module>
    label = '{0} @ {1}'.format(objname[j], tl[j]))
IndexError: list index out of range

**Comment by bd-j** [comment]
ah, on my machine I have more SFHs, so the bug went unnoticed.  should be fixed as of bc06686d83210e767d82
